### ISSUE TITLE
Why is your ground truth applied result so weird ?

### ISSUE THREAD

**Issue by amandayeyan** [matteo-rizzo/fc4-pytorch#7]

**Comment by matteo-rizzo** [comment]
Hi! Could you please enlarge on your question? Thank you

**Comment by amandayeyan** [comment]
> 

Hi matteo, thanks for your great work done. I am referring to the correction image. The corrected image looks pink ? 
![image](https://user-images.githubusercontent.com/18046926/143159989-ce2c7321-c19c-42b9-87f7-634ccd47445d.png)

**Comment by amandayeyan** [comment]
How does this image look like after you finish 2000 epoch training ?

**Comment by matteo-rizzo** [comment]
Hi! I guess you cropped that example from the README. That correction is based on some illuminant estimated by the trained model, which could still get a relatively high angular error (it's probably the case for this image and that's why it's pinkish). You can try and test other inputs and see how they look like, usually when the angular error is around 1 or less the correction should look very similar to the ground truth correction, which is not included in the visualization. I hope this clarifies the issue, let me know if you have other questions!
